version: "1.0"
stages:
  - prepare
  - build
  - test
  - integration
  - deploy
steps:
  preparation:
    stage: prepare
    title: Prepare build
    description: Export environment variables needed by the build
    image: crystallang/crystal
    commands:
      - echo "Build ID is $CF_BUILD_ID"
      - cf_export PROJECT=$(basename -s .git `git config --get remote.origin.url`)
      - cf_export GIT_HASH=$CF_REVISION
      - cf_export RELEASE_VERSION=$(shards version .)

  build_image:
    stage: build
    type: build
    description: Build Docker image
    image_name: impatienttraveller/${{PROJECT}}

  push_snapshot:
    stage: deploy
    type: push
    title: Push snapshot
    description: Push snapshot Docker image to the Docker Registry
    candidate: ${{build_image}}
    tags:
      - develop
      - ${{GIT_HASH}}
    when:
      branch:
        ignore:
          - master

  push_release:
    stage: deploy
    type: push
    title: Push release
    description: Push release Docker image to the Docker Registry
    candidate: ${{build_image}}
    tags:
      - latest
      - ${{RELEASE_VERSION}}
    when:
      branch:
        only:
          - master
