version: "3"

networks:
  app-tier:
    driver: bridge

services:
  property-catalogue:
    depends_on:
      - mongo-db
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile
      image: ss_property_catalogue

  mongo-db:
    image: mongo:4.1.6
    restart: always
    networks:
      - app-tier
    environment:
      - MONGODB_USERNAME=propertycatalogue
      - MONGODB_PASSWORD=pa55w0rd!
      - MONGODB_DATABASE=property_catalogue
      - MONGODB_EXTRA_FLAGS=--smallfiles --logpath=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/bitnami
